### ISSUE TITLE
Impressum erstellen

### ISSUE THREAD

**Issue by keimlink** [CodeforLeipzig/luftqualitaet_sachsen#10]
Betreiber ist die OKF, Datenquelle und unsere Lizenz angeben (cc-by). Auch wichtig wegen der Inhalte, die wir aus der Wikipedia übernehmen (siehe #16).

**Comment by keimlink** [comment]
@kater169 Hast du auch die Lizenz angegeben? Oder machst du das wenn du Issue #16 umsetzt?

**Comment by kater169** [comment]
Das würde ich dann mit #16 machen
