### ISSUE TITLE
README und Dokumentation verbessern

### ISSUE THREAD

**Issue by keimlink** [CodeforLeipzig/luftqualitaet_sachsen#17]
README und Dokumentation sollten erklären, wozu das Projekt dient und wie eine Entwicklungsumgebung eingerichtet wird.

Nachdem ein virtualenv erstellt wurde sieht eine Installation so aus:

```
$ make install-dev
$ make create-db
$ make migrate
$ python luftqualitaet_sachsen/manage.py loaddata measuring_stations
$ python luftqualitaet_sachsen/manage.py loaddata indicated_values
```

Danach kann der Entwicklungsserver gestartet werden:

```
$ make runserver
```

Livedaten können so geladen werden:

```
$ make fetch
```

**Comment by plumps** [comment]
Hi ,
hier meine ersten Schritte die Installation zu vereinfachen und die Lücken in der Dokumentation zu schließen https://github.com/plumps/luftqualitaet_sachsen/tree/adding-vagrant .

Leider scheitere ich im Moment an dem create-db target, hast du eine Idee? an user/superuser liegt es nicht

    (luftverschmutzung_sachsen)vagrant@codeforleipzig:/vagrant$ make create-db
    createuser -d -e -P luftqualitaet_sachsen
    Enter password for new role: 
    Enter it again: 
    createuser: could not connect to database postgres: FATAL:  role "vagrant" does not exist
    make: *** [create-db] Error 1
   
DB läuft auch:
    (luftverschmutzung_sachsen)vagrant@codeforleipzig:/vagrant$ /etc/init.d/postgresql status
    9.3/main (port 5432): online

**Comment by keimlink** [comment]
Wenn ich es richtig sehe führst du `make create-db` als Benutzer `vagrant` aus. In der Regel hat aber nur der Benutzer `postgres` die dafür notwendigen Rechte. So sollte es klappen:
```
$ sudo -u postgres make create-db
```

**Comment by plumps** [comment]
PR ist fertig :-)
