### ISSUE TITLE
Shapes von allen deutschen Bundesländern

### ISSUE THREAD

**Issue by kater169** [CodeforLeipzig/luftqualitaet_sachsen#20]
Wir sollten in die Karte die Ländergrenzen der einzelnen Bundesländer anzeigen.
Beim Klick auf einen Ländernamen sollte die Karte automatisch rein Zoomen.

**Comment by kater169** [comment]
Shapes file wurde ersetzt und angezeigt

**Comment by keimlink** [comment]
:thumbsup:
